#!/bin/bash
# v1.6 hardening: turn on mosquitto password + TLS, explicit opt-in — NOT run
# by install.sh. Run from nvr-rk3576:  scripts/harden_mosquitto.sh <user>
#
# Secures BOTH listeners (allow_anonymous is top-level, so plaintext 1883
# also refuses anonymous) and installs the panel's shared self-signed cert
# into /etc/mosquitto/certs/ with mosquitto-owner perms — the broker runs as
# its own system user and cannot traverse a private home dir.
set -e
cd "$(dirname "$0")/.."

[ $# -eq 1 ] || { echo "usage: $0 <username>"; exit 1; }
USER="$1"

[ -f config/panel.crt ] && [ -f config/panel.key ] || {
    echo "no TLS cert yet — run scripts/gen_tls_cert.sh first"; exit 1;
}

# Create/refresh the broker user (prompts for the password).
sudo mosquitto_passwd -c /etc/mosquitto/passwd "$USER"

# Install the shared cert for the mosquitto user (644 cert, 640 key).
sudo install -o root -g root -m 644 config/panel.crt /etc/mosquitto/certs/panel.crt
sudo install -o root -g mosquitto -m 640 config/panel.key /etc/mosquitto/certs/panel.key

sudo tee /etc/mosquitto/conf.d/falcon-tls.conf > /dev/null <<EOF
# Generated by scripts/harden_mosquitto.sh — TLS + password auth for the
# Falcon NVR. allow_anonymous false is top-level, so it applies to every
# listener (1883 and 8883).
allow_anonymous false
password_file /etc/mosquitto/passwd

listener 8883
certfile /etc/mosquitto/certs/panel.crt
keyfile /etc/mosquitto/certs/panel.key
EOF

sudo systemctl restart mosquitto
echo "mosquitto hardened: TLS on 8883, password auth required on all listeners."
echo "Connect with: mosquitto_sub -p 8883 --cafile config/panel.crt -u '$USER' -t 'nvr/#'"
echo "Remember to set the panel's mqtt section in config/config.yaml to"
echo "port 8883, use_tls: true, and this username/password."
